site_name: I3Val Input Validation
site_description: Ilja's Initiative for Input Validation
site_author: SYSTOPIA
repo_url: https://github.com/systopia/Contact-Update-Queue

theme:
  name: material

nav:
- 'Home': index.md
- 'Configuration': configuration.md
- 'Registering change requests': registering-change-requests.md
- 'Processing change requests': processing-change-requests.md

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark

plugins:
  - search:
      lang: en
